/*
=========================
EXPLORATORY DATA ANALYSIS
=========================
Purpose of the Script:
This script uses the data from gold layer in datawarehouse project.
It consists of:
-Basic exploration of the database
-identifying tables, columns in the database
-Exploring dimensions, measures in the tables
- Basic analysis to understand the business
*/

USE datawarehouse;

--Database exploration
SELECT *
FROM INFORMATION_SCHEMA.tables;
--around 15 tables

--Exploring the columns in each table
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME= 'dim_customers';

--Dimension Exploration
SELECT DISTINCT customer_country
FROM gold.dim_customers

SELECT DISTINCT category,sub_category,product_name
FROM gold.dim_products
ORDER BY 1,2,3;

--Date Exploration
SELECT MAX(customer_created_on), MIN(customer_created_on)
FROM gold.dim_customers

SELECT MAX(order_date) latest_order_date, 
MIN(order_date) earliest_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) order_range_year
FROM gold.fact_sales

SELECT DATEDIFF(year,MAX(customer_birthdate),GETDATE()) youngest_customer,
DATEDIFF(year,MIN(customer_birthdate),GETDATE()) oldest_customer
FROM gold.dim_customers

--Measure Exploration
--total sales
SELECT
SUM(sale_amount) total_sales
FROM gold.fact_sales;

--total items sold
SELECT 
SUM(quantity) total_items_sold
FROM gold.fact_sales;

--Average selling price
SELECT 
AVG(price) avg_item_price
FROM gold.fact_sales;

--total number of orders
SELECT 
COUNT(DISTINCT order_number) total_no_orders
FROM gold.fact_sales;

--Total number of products
SELECT 
COUNT(DISTINCT product_id) total_products
FROM gold.dim_products;

--total number of customers
SELECT 
COUNT(customer_id) total_customers
FROM gold.dim_customers;

--total no of customers that placed the order
SELECT
COUNT(DISTINCT customer_key) total_customers_ordered
FROM gold.fact_sales

--Generating a report that shows all key metrics of the business
SELECT 
'total_sales' Name_of_measure,
SUM(sale_amount) value_of_measure
FROM gold.fact_sales
UNION ALL
SELECT 
'total_items_sold',
SUM(quantity) 
FROM gold.fact_sales
UNION ALL
SELECT 
'avg_item_price',
AVG(price) 
FROM gold.fact_sales
UNION ALL
SELECT 
'total_no_orders',
COUNT(DISTINCT order_number) 
FROM gold.fact_sales
UNION ALL
SELECT 
'total_products',
COUNT(DISTINCT product_id) 
FROM gold.dim_products
UNION ALL
SELECT 
'total_customers',
COUNT(customer_id) 
FROM gold.dim_customers
UNION ALL
SELECT
'total_customers_ordered',
COUNT(DISTINCT customer_key) 
FROM gold.fact_sales

--Magnitude
--total customers by countries
SELECT
customer_country,
COUNT(customer_id) total_customers
FROM gold.dim_customers
GROUP BY customer_country
ORDER BY total_customers DESC

--total customers by gender
SELECT 
customer_gender,
count(customer_id) total_customer
FROM gold.dim_customers
GROUP BY customer_gender
ORDER BY total_customer DESC

--total products per category
SELECT
category,
COUNT( DISTINCT product_id) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT( DISTINCT product_id) DESC

--avg costs per category
SELECT
category,
avg(product_cost) avg_price
FROM gold.dim_products
GROUP BY category
ORDER BY avg_price DESC

--total revenue generated by each category
SELECT
p.category,
SUM(s.sale_amount) total_reveune
FROM gold.fact_sales s  
LEFT JOIN gold.dim_products p
ON s.product_key=p.product_key
GROUP BY p.category
ORDER BY total_reveune DESC

--total reveune generated by each customer
SELECT
c.customer_name,
SUM(s.sale_amount) total_reveune
FROM gold.fact_sales s  
LEFT JOIN gold.dim_customers c
ON c.customer_key=s.customer_key
GROUP BY c.customer_key, c.customer_name
ORDER BY total_reveune DESC

--what is the distribution of sold items across countries
SELECT
c.customer_country,
SUM(s.quantity) total_items_sold
FROM gold.fact_sales s  
LEFT JOIN gold.dim_customers c
ON s.customer_key=c.customer_key
GROUP BY c.customer_country
ORDER BY total_items_sold DESC

--ranking
--TOP 5 products with highest revenue
SELECT TOP 5
p.product_key,
p.product_name,
SUM(s.sale_amount) total_reveune
FROM gold.fact_sales s  
LEFT JOIN gold.dim_products p
ON s.product_key=p.product_key
GROUP BY p.product_key,p.product_name
ORDER BY total_reveune DESC

--worst 5 performing products
SELECT TOP 5
p.product_key,
p.product_name,
SUM(s.sale_amount) total_reveune
FROM gold.fact_sales s  
LEFT JOIN gold.dim_products p
ON s.product_key=p.product_key
GROUP BY p.product_key,p.product_name
ORDER BY total_reveune ASC

--TOP 10 customers who generated the highest revenue
SELECT TOP 10
c.customer_name,
SUM(s.sale_amount) total_reveune
FROM gold.fact_sales s  
LEFT JOIN gold.dim_customers c
ON c.customer_key=s.customer_key
GROUP BY c.customer_key, c.customer_name
ORDER BY total_reveune DESC

--3 customers with fewest orders
SELECT TOP 3
c.customer_key,
c.customer_name,
COUNT(DISTINCT s.order_number) total_orders
FROM gold.fact_sales s  
LEFT JOIN gold.dim_customers c
ON c.customer_key=s.customer_key
GROUP BY c.customer_key, c.customer_name
ORDER BY total_orders asc
